name: snakemake_mirdeep2
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  # Core Python + env tooling
  - python=3.12
  - pip

  # Workflow + QC tools
  - snakemake=8.11.3
  - fastqc=0.12.1
  - multiqc=1.13

  # miRNA mapping / prediction
  - mirdeep2=2.0.0.8
  - bowtie=1.3.1

  # Misc
  - wget
  - perl=5.32.1

  # R base
  - r-base
  - r-essentials

  # CRAN-like packages via conda-forge
  - r-tidyr
  - r-readr
  - r-caret
  - r-ggplot2
  - r-ggrepel
  - r-scales
  - r-dplyr
  - r-stringr
  - r-optparse
  - r-tibble
  - r-purrr
  - r-broom

  # Bioconductor packages
  - bioconductor-edger
  - bioconductor-limma
  - bioconductor-deseq2
  - bioconductor-enhancedvolcano
